### PR TITLE
Dat classy use of background image :zap:

### PR DESCRIPTION
**Pull request by jglovier**

### CODE REVIEW

**Comment by parkr** [comment]
THIS PR THO :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart:

**Comment by parkr** [comment]
Everything looks the same at the moment, even after re-compiling the Sass, so imma go ahead and wait until you give me the :tada: that it's finished.

For your reference, run this as you dev:

``` bash
$ JEKYLL_SERVE=true bundle exec guard
```

:grinning:

**Comment by jglovier** [comment]
> Everything looks the same at the moment, even after re-compiling the Sass, so imma go ahead and wait until you give me the :tada: that it's finished.

Strange - yeah I wasn't able to get it to change locally either, but I just assumed that it was because I wasn't running the Sass right, but it would just work in production. So two question:
1) So you're not running the coming Jekyll 2.0 version of Sass support, are you? I.e. is this a non-native implementation of Jekyll Sass support?
2) I ran `$ JEKYLL_SERVE=true bundle exec guard` but still no updating .css files. What could I still be missing?

**Comment by jglovier** [comment]
Okay, all set. :zap: :boom:

**Comment by parkr** [comment]
Thanks for the PR!! :sparkles: :heart: Looks awesome. Have 2 quick questions:
1. I'm curious about the change of the font family of the site title. Does it increase readability or help with cognitive differentiation?
2. I would love to show off the background a little more. What do you think about extending the top margin or somehow using it as an accent?

For reference, here's what I'm looking at:

screen shot 2014-01-28 at 1 37 50 pm

screen shot 2014-01-28 at 1 37 52 pm

**Comment by jglovier** [comment]
> I'm curious about the change of the font family of the site title. Does it increase readability or help with cognitive differentiation?

Yeah, in general you don't want to use the same exact typeface, font-size, font-style, etc on everything. That's Typography 101 - use of differing font-families, sizes, etc are a way to communicate visual hierarchy. The document title should stand out as such.

> I would love to show off the background a little more. What do you think about extending the top margin or somehow using it as an accent?

I wouldn't. You could drop it down a bit, but with a really noisy background like that it's just going to be distracting. Showing it off in a thin manner is a very tasteful way to use a noise background yet not draw attention away from the site's content, which is the real star of the show. Always keep focus on the site content when content is the :star:.

> For reference, here's what I'm looking at:

Interesting in that second screen shot the two sections are floating next to each other. I didn't realize those links actually used the post.html layout - for some reason I just assumed they went directly to your resource. I'll tweak the styles a tad on that page.

**Comment by jglovier** [comment]
Also, FWIW, using a mono-space font like Consolas for body copy is generally a design faux pas, because mono-space fonts are optimized for reading things like code, but are crappy for reading long sections of text (a.k.a. body copy).

In this case, since your just posting links and not actual articles, it's not that big of a deal so I left it as is. Plus, Consolas is one of the lovelier monospace fonts.

**Comment by jglovier** [comment]
There's some other things I'd do with the layout, but it includes removing that css grid system so I should really make a different branch & PR for that. Also, I'd like to get you using Sass properly :trollface: ([SMACSS](http://smacss.com/) modules ftw).

**Comment by parkr** [comment]
> Yeah, in general you don't want to use the same exact typeface, font-size, font-style, etc on everything. That's Typography 101 - use of differing font-families, sizes, etc are a way to communicate visual hierarchy. The document title should stand out as such.

Ok, awesome! I have no idea what I'm doing so I just wanted to ask. :smiley: 

> I wouldn't. You could drop it down a bit, but with a really noisy background like that it's just going to be distracting. Showing it off in a thin manner is a very tasteful way to use a noise background yet not draw attention away from the site's content, which is the real star of the show. Always keep focus on the site content when content is the :star:.

Reason enough for me! Thanks for the explanation!! :sparkles: 

> Interesting in that second screen shot the two sections are floating next to each other. I didn't realize those links actually used the post.html layout - for some reason I just assumed they went directly to your resource. I'll tweak the styles a tad on that page.

Yeah I think they're broken on the main page (i.e. not localhost)... womp. What do you have in mind?

> Also, FWIW, using a mono-space font like Consolas for body copy is generally a design faux pas, because mono-space fonts are optimized for reading things like code, but are crappy for reading long sections of text (a.k.a. body copy).

Very interesting!! As a constantly-in-vim developer, I am used to reading long blocks of text in monospaced font (incidentally, Consolas for Powerline).

I'd very much like your help in leveling up my designing & Sass skillz – my background is in designing and implementing API's, so please forgive my naiveté here! :smiley_cat: Any and all PR's you are willing to submit will be happily received :sparkling_heart:

**Comment by parkr** [comment]
YAY! And now that I look at this more, it seems like the navigation-y stuff on the right should really be pushed above the link or something to its own line and made smaller (text-wise):

screen shot 2014-01-28 at 3 56 43 pm

**Comment by jglovier** [comment]
> I'd very much like your help in leveling up my designing & Sass skillz – my background is in designing and implementing API's, so please forgive my naiveté here! :smiley_cat: Any and all PR's you are willing to submit will be happily received :sparkling_heart:

I gotchu dawg! :zap:

And believe me, I know dat feel. That's exactly how I feel everytime I come running to you or others for help with shell stuff, scripting, etc. We all have our strengths. :smile: 

FWIW, this is one of the things I freaking :heart: about the world of open source (and GitHub in particular) - it provides a venue for us all to work in our areas of strength, and use those areas to help one another.

**Comment by jglovier** [comment]
> YAY! And now that I look at this more, it seems like the navigation-y stuff on the right should really be pushed above the link or something to its own line and made smaller (text-wise):

Yeah. I'll open another PR soon with some layout refactoring.

**Comment by jglovier** [comment]
Ruh roh - just noticed the links are 404ing: http://blog.parkermoore.de/2014/01/28/the-pattern-library.html

**Comment by parkr** [comment]
> Ruh roh - just noticed the links are 404ing

Yuuuurp. I tend to work with absolute links so it's actually asking for what would be a blog post from parkr.github.com (the repo), which don't exist. Just added a `CNAME` to `webdev.parkermoo.re` :boom: They should work from there!

> And believe me, I know dat feel. That's exactly how I feel everytime I come running to you or others for help with shell stuff, scripting, etc. We all have our strengths. :smile: FWIW, this is one of the things I freaking :heart: about the world of open source (and GitHub in particular) - it provides a venue for us all to work in our areas of strength, and use those areas to help one another.

THIS :point_up:  :zap: Couldn't agree more. :shipit: :together:

**Pull request merged**
